name: Bug Report
description: File a bug report to help us improve LocalAgentWeaver
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checks
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true
        - label: I am using a supported version of LocalAgentWeaver
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Frontend (Next.js/React)
        - Backend (FastAPI)
        - Authentication
        - LLM Integration (Ollama/LM Studio)
        - Document Processing
        - Teams/Agents Management
        - Database
        - Docker/Infrastructure
        - Other
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide details about your environment
      value: |
        - OS: [e.g., Windows 11, macOS 14, Ubuntu 22.04]
        - Browser: [e.g., Chrome 119, Firefox 120, Safari 17]
        - LocalAgentWeaver Version: [e.g., v0.1.0]
        - LLM Provider: [e.g., Ollama, LM Studio]
        - LLM Model: [e.g., llama3:latest]
        - Docker Version: [e.g., 24.0.6]
        - Docker Compose Version: [e.g., 2.23.0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Please provide relevant logs or error messages
      placeholder: |
        Paste any relevant logs, error messages, or console output here.
        Use code blocks (```) for better formatting.
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop screenshots here or paste URLs

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...